-- 0004_auto_skip.sql — '자동단축초' 설정 추가 (2026-09-05, 사용자 결정).
--
-- 모든 모둠이 답을 냈거나(문제 단계) 베팅을 확정했으면(베팅 단계), 그때부터 이 초만큼만
-- 더 두고 다음 단계로 넘어간다. 마지막으로 제출한 모둠이 정답·해설을 볼 시간이다.
-- 0 이면 자동 단축을 끈다 (src/game/config.ts 의 SETTING_RANGE — 0~30).
--
-- ⚠️ 토론 단계에는 적용되지 않는다. 토론 180초가 이 수업의 실체다 (MIGRATION §1).
--
-- INSERT OR IGNORE 인 이유는 0002 와 같다 — 선생님이 관리 화면에서 고친 값을
-- 이 파일이 다시 돌면서 조용히 덮으면 안 된다.
INSERT OR IGNORE INTO settings (key, value, label) VALUES ('autoSkipSeconds', '5', '자동단축초');
